### ISSUE TITLE
CLI flag --include-dev overrides includeDevDependencies configuration parameter

### ISSUE THREAD

**Issue by ben-eb** [tobysmith568/license-cop#176]
Hello 👋 

Thanks for your work on this project, it looks super useful. I've run into an issue where `includeDevDependencies` (or `devDependenciesOnly`) are not loaded by the CLI due to the argument parsing:

https://github.com/tobysmith568/license-cop/blob/02a3ff10c0df821d3e15c4c5938a7884b1e24a9c/packages/license-cop/src/lib/cli/commands/main.ts#L14-L15

Due to the way the configuration resolves these values the default CLI options are preferred over external configuration:

https://github.com/tobysmith568/license-cop/blob/02a3ff10c0df821d3e15c4c5938a7884b1e24a9c/packages/license-cop/src/lib/cli/commands/main.ts#L45-L46

This is because the value is not `null` or `undefined` but `false` instead (so the value in the configuration cannot be read).

I can fix by passing `--include-dev` and `--dev-only` to the CLI as needed but this usage isn't documented (and I suspect this is a bug due to the configuration parameters being documented).

Thanks 🙂

**Comment by tobysmith568** [comment]
Hey @ben-eb ,

Thanks for raising this. If you want a fix out asap then feel free to raise a PR for it, else I'll have a look into it within the next few days.

**Comment by tobysmith568** [comment]
Hey @ben-eb ,

A fix for this has just gone out in 1.6.3

Please feel free to re-open/reply if you have any further issues!

**Comment by ben-eb** [comment]
Many thanks, that resolves my issue 👍
